# Copyright (C) 2016-2018 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image: docker:git
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

.docker_gitlab: &docker_gitlab
  before_script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

.docker_hub: &docker_hub
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS

build:gitlab:
  <<: *docker_gitlab
  stage: build
  script:
    # - docker build -t "$CI_REGISTRY_IMAGE:1.x.latest" 1.8
    # - docker push "$CI_REGISTRY_IMAGE:1.x.latest"
    # - docker build -t "$CI_REGISTRY_IMAGE:latest" 2.0
    # - docker push "$CI_REGISTRY_IMAGE:2.0.latest"
    # - docker build -t "$CI_REGISTRY_IMAGE:latest" 2.1
    # - docker push "$CI_REGISTRY_IMAGE:2.1.latest"
    # - docker build -t "$CI_REGISTRY_IMAGE:latest" 2.2
    # - docker push "$CI_REGISTRY_IMAGE:2.2.latest"
    # - docker build -t "$CI_REGISTRY_IMAGE:latest" 2.2 -f 2.2/Dockerfile.arm64
    # - docker push "$CI_REGISTRY_IMAGE:2.2.arm64.latest"
    - make build version=2.2
    - make build version=2.2 arch=arm64
  only:
    - master

build:hub:
  <<: *docker_hub
  stage: build
  script:
    - docker build -t "zeiot/$CI_PROJECT_NAME:1.x.latest" 1.8
    - docker push "zeiot/$CI_PROJECT_NAME:1.x.latest"
    - docker build -t "zeiot/$CI_PROJECT_NAME:latest" 2.0
    - docker push "zeiot/$CI_PROJECT_NAME:2.0.latest"
    - docker build -t "zeiot/$CI_PROJECT_NAME:latest" 2.1
    - docker push "zeiot/$CI_PROJECT_NAME:2.1.latest"
    - docker build -t "zeiot/$CI_PROJECT_NAME:latest" 2.2
    - docker push "zeiot/$CI_PROJECT_NAME:2.2.latest"
    - docker build -t "zeiot/$CI_PROJECT_NAME:latest" 2.2 -f 2.2/Dockerfile.arm64
    - docker push "zeiot/$CI_PROJECT_NAME:2.2.arm64.latest"
  only:
    - master

deploy:gitlab:
  <<: *docker_gitlab
  stage: deploy
  script:
    - export VERSION=$(grep ' VERSION' 1.8/Dockerfile|awk -F" " '{ print $3 }')
    - echo ${VERSION}
    - docker build -t "$CI_REGISTRY_IMAGE:v${VERSION}" 1.8
    - docker push "$CI_REGISTRY_IMAGE:v${VERSION}"
    - export VERSION=$(grep ' VERSION' 2.0/Dockerfile|awk -F" " '{ print $3 }')
    - echo ${VERSION}
    - docker build -t "$CI_REGISTRY_IMAGE:v${VERSION}" 2.0
    - docker push "$CI_REGISTRY_IMAGE:v${VERSION}"
    - export VERSION=$(grep ' VERSION' 2.1/Dockerfile|awk -F" " '{ print $3 }')
    - echo ${VERSION}
    - docker build -t "$CI_REGISTRY_IMAGE:v${VERSION}" 2.1
    - docker push "$CI_REGISTRY_IMAGE:v${VERSION}"
  only:
    - tags

deploy:hub:
  <<: *docker_hub
  stage: deploy
  script:
    - export VERSION=$(grep ' VERSION' 1.8/Dockerfile|awk -F" " '{ print $3 }')
    - echo ${VERSION}
    - docker build -t "zeiot/$CI_PROJECT_NAME:v${VERSION}" 1.8
    - docker push "zeiot/$CI_PROJECT_NAME:v${VERSION}"
    - export VERSION=$(grep ' VERSION' 2.0/Dockerfile|awk -F" " '{ print $3 }')
    - echo ${VERSION}
    - docker build -t "zeiot/$CI_PROJECT_NAME:v${VERSION}" 2.0
    - docker push "zeiot/$CI_PROJECT_NAME:v${VERSION}"
    - export VERSION=$(grep ' VERSION' 2.1/Dockerfile|awk -F" " '{ print $3 }')
    - echo ${VERSION}
    - docker build -t "zeiot/$CI_PROJECT_NAME:v${VERSION}" 2.1
    - docker push "zeiot/$CI_PROJECT_NAME:v${VERSION}"
  only:
    - tags

